### ISSUE TITLE
Bug: Localization files are not correctly loaded in mods?

### ISSUE THREAD

**Issue by ashifolfi** [CitadelCore/Portal-2-Enhanced#1350]
### Describe the bug

I noticed that while adding some localization strings to the file to use in panorama that it would act like they didn't exist. Didn't matter what the token was it wasn't able to localize it. however using tokens that were present in vanilla p2ce or p2 worked just fine???

### Issue Map

N/A

### To Reproduce

1. create a mod
2. add new tokens and strings to the file
3. try and use them in panorama
4. watch it fail

**Comment by Luke18033** [comment]
Note that one of the language files is loaded based on the mod folder name, so you need to call it `mymod_english.txt` or whatever for it to work.

**Comment by ashifolfi** [comment]
> Note that one of the language files is loaded based on the mod folder name, so you need to call it `mymod_english.txt` or whatever for it to work.

Hey! I just noticed this and thought I'd mention that I had been doing this and it wasn't working. It's what led to me having made the issue in the first place in fact.

**Comment by Luke18033** [comment]
Does it also not work if you just call it `p2ce_english`?
