### ISSUE TITLE
Laser Collision keyvalue on env_portal_laser

### ISSUE THREAD

**Issue by vrad-exe** [CitadelCore/Portal-2-Enhanced#40]
This would allow disabling it on a per-laser basis, instead of having to set the console variable (which persists across maps, and in Co-op requires sv_cheats).

**Comment by Luke18033** [comment]
An option to have players *block* the laser instead of passing through it would also be nice, maybe as mode 2. This should default to off, though see if you can get it to use the old behavior in vanilla maps for backwards-compatibility.

**Comment by SpyceTewan** [comment]
No I only added this for damage so far

**Comment by Luke18033** [comment]
Should I open a separate issue for the blocking mode?
